IMA-WorldHealth/bhima-1.X

server/lib/parser.js
For SQL queries created by validate.process(dependencies), add support for SQL 'AS' aliasing using a '::' syntax.  For instance
dependencies.patient = {
tables :  { 
'patient' : 
columns : ['first_name', 'last_name::surname']
}
This will expand out to:
SELECT patient.first_name, patient.last_name as surname, from patient...
=> Added support for 'as' aliasing in SQL select queries

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/partials/templates/findpatient.tmpl.html
The 'Find patient' directive (findPatient) was displaying 'Find by Debitor ID' for the translation item ENTER_DEBITOR_ID. This was translated as "Find by Patient ID" in english but 'Cherchez Debitor ID" in french. The english seemed correct so I changed the translation tag to ENTER_PATIENT_ID and fixed the french translation to match the english translation.
This directive should be general and seems to work that way, although the directive code does seem to reference debitor info. Not sure if some cleanup/updating is necessary on this since it seems to work okay.
=> Fixed translation issue with find-patient directive

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/js/services/util.js, client/src/partials/patient_edit/edit_patient.js, client/src/partials/patient_registration/patient.html, client/src/partials/patient_registration/patient.js
Added a global value for the minimum patient DOB in the util service:    util.minimumPatientDate.
Updated DOB year-out-of-range error message to include tokens for <min> and <max> which are replaced in the form controller code.
Updated patient register/edit forms to use util.minimumPatientDate and eliminate any hardcoded dates in the form html and controller code.
=> Remove hardcoded minimum birth year in patient register/edit forms

utilities/patient/clean_names_db.js
Added a utility (utilities/patient/clean_names_db) that will clean up the names in database. It will remove an 'rien' first names and normalize the capitalization of all patient names. When the utility is run, it creates an SQL file that can be examined before being applied to the database.
=> New utility script to clean up patient names

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/partials/accounts/create_account/create.js
Fixes and cleaned up terms for Account management page.  Display actual account type, not a number.  Other improvements.  French updates done with Dedrick's help. 
Removed obsolete translation items orphaned by removal of fiscal year closing code.
=> Improve usability of Account management page and remove obsolete translation items

client/src/i18n/en.json, client/src/i18n/fr.json, server/controllers/report.js
Translated Serice Usage report items into English.
Fixed error in fr.json file:  Duplicated top-level "SALES" sections were preventing correct recognition of new 
'distributable' translation items.
=> Service Usage Report translations

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/js/directives/findpatient.js, client/src/js/services/exchange.js, client/src/js/services/validate.js, client/src/partials/patient_edit/edit_patient.html, client/src/partials/patient_edit/edit_patient.js
Currently, when editing a patient, once you start editing a patient, you cannot switch to another patient without going to some other page. 
This PR adds a button on the right side of the Patient Details edting area (only when editing).  The user can click on the button to switch back to the search mode to find another patient to edit.
Currently when the user is editing a patient and clicks on the  main menu 'Edit Patient Details' item, nothing happens.  I'm sure it would be possible to fix this, but having an button for that purpose may be simpler for users.
Also disabled the automatic logging of the exchange rate on ever startup.
=> Enable edit patient restart

client/src/partials/reports/account_statement/account_statement.html, client/src/partials/reports/account_statement/account_statement.js
The account selector on the Report/Account Statement page shows the database ID number in the field once it is selected (before submission).  This mod changes it to display the Account name and number (similar to the drop-down menu during selection).  Once the user presses the [Submit] button, this field is cleared in case the user wants to start another search.
=> Account statement num fix

.travis.yml, README.md, package.json, server/lib/util.js, server/test/util.spec.js
In this PR:
- `npm test` now runs server-side mocha tests
- .travis.yml added for future Travis CI integration
- tests for `lib/util.js` added
- rm a few, irrelevant features in util.js
- FIX: util.toDistinctValues() no longer results in an error for arrays with duplicate values.
=> Integrate npm to run tests

client/src/partials/reports/primary_cash/income/income_report.js
The Incomes report was reporting a javascript error on the startup if no cashbox is selected immediately.   This fix avoids errors due to trying to access undefined values.
=> Fix small income report bug

client/src/i18n/fr.json
In this PR, I fixed a gulp warning on fr.json missing entry
=> Fixing fr.json entry missing

server/models/updates/synt.sql
In this PR, we have added a primary_cash_module in synt.sql for payday_advance
=> Fixing payday_advance error when primary_cash_module missing

server/models/updates/synt.sql
- Fixed an error which occured in monthly_balance_report
- Added an entry in synt.sql for adding class in each account
=> Fixing monthly balance report data lacking due to missing account class

server/lib/sanitize.js, server/test/sanitize.spec.js, server/test/set.spec.js
In this PR, I've added tests for sanitize.js that run as part of the bhima build.  The sanitize.js module __should__ be deprecated, but while we extract it from the server code, we should make sure that it continues working properly.
Partially fixes #306.
=> Server Tests: Sanitize.js

client/src/partials/reference/reference.html, client/src/partials/reference/reference.js
improve and fix error of reference form
=> improve and fix error of reference form

TODOs.md, client/src/i18n/en.json, client/src/i18n/fr.json, client/src/js/services/generalledger.js, client/src/js/services/gridhelper.js, client/src/partials/journal/journal.grid.js, client/src/partials/journal/journal.utilities.js, client/src/partials/reports/ledger/general_ledger.css, client/src/partials/reports/ledger/general_ledger.html, client/src/partials/reports/ledger/general_ledger.js, server/config/routes.js, server/controllers/ledgers/general.js
In this PR:
- Sorting, column filtering and text filtering are implemented on the General Ledger.
- Added a TODOs to keep track of work in progress
I've introduced two new services, `GridHelperService` and `GeneralLedgerService` to be responsible to providing functions common to SlickGrid and load data into the General Ledger.  In the future, we can use `GridHelperService` to maximize code reuse in the Posting Journal.
**NOTE**  This does not implement printing on the General Ledger.  That is a design issue that will have to be approached soon.
Partially addresses #571.
=> Impliment sorting/filtering on General Ledger

client/gulpfile.js
In this PR:
- Linting is no longer required for building the project.  You should still type `gulp lint` before submitting a PR, but it is unnecessary to run each time.
**Motivation:** On my (fairly high-powered) machine, it takes an average of 10 seconds to lint the whole repository.  See the attached output.  This leads to unnecessary wait for small changes.  We already have TravisCI to check these errors when submitting PRs.  (See #563)
```bash
[15:32:44] ⲗ →  for i in `seq 1 10`; do gulp lint; done
[15:33:38] Using gulpfile ~/code/bhima/client/gulpfile.js
[15:33:38] Starting 'lint'...
/home/jniles/code/bhima/client/src/partials/cash/extra_payment/extra_payment.js: line 182, col 20, Extending prototype of native object: 'Array'.
1 error
[15:33:47] Finished 'lint' after 9.7 s
[15:33:48] …
```
=> Remove JS linting from default gulp

client/src/js/directives/findpatient.js, client/src/partials/patient/group/assignment.html, client/src/partials/patient/group/assignment.js, client/src/partials/templates/debtorListItem.tmpl.html, client/src/partials/templates/findpatient.tmpl.html, server/config/routes.js, server/controllers/patient.js
This PR completely re-writes the find-patient directive to be lighter weight.  It uses a series of GET requests on the input to download and filter the data from the database, rather than a single pull of all patients in the database and client-side filtering.  Only 10 values are sent by MySQL at a time.
Additionally, we compliment the results with the `SOUNDEX()` MySQL algorithm to match potentially misspelled words.  This is interesting, but may be confusing for users and will need to be reviewed in user trials.
**NOTE** This PR is for concept review only.  The way we handle authentication is thoroughly broken and sometimes logs a user out when they search for an invalid reference.
=> Find-Patient Directive Re-write

server/controllers/patient.js
As suggested by @lomamech, the find patient directive now prioritizes last names to be more culturally appropriate.
=> Prioritize last name in find-patient directive

plugins/pluginManager.js, server/app.js
This PR fixes a critical bug that allowed `fork()`ed processes to live on past the termination of the parent server.  Additionally, the changes suggested by @DedrickEnc in #554 have been incorporated.
=> FIX: PluginManager kills child processes on exit

client/gulpfile.js
This PR makes the default gulp command run gulp watch automatically.
=> Run gulp watch by default

client/src/partials/journal_voucher/journal_voucher.js, server/app.js, server/controllers/finance.js, server/controllers/uncategorised.js, server/lib/db.js
This PR fixes a critical bug that halted journal vouchers from posting due to a broken reference to `req.session.project_id`.  It has been updated with the correct syntax.  Also, `getTransactionId()` has been greatly improved.
=> FIX: broken req.session references

client/src/partials/inventory/distribution/distribution.html, client/src/partials/stock/exit/distribution.html
update the function initialiseDistributionDetails in initialiseDistributionDetails(patient)
=> Fix stock distribution

package.json
You can now use `npm run app` from the top level to build and deploy build.  It's easier than lots of `cd`s.
=> Add `npm run app` to ease build process

client/src/js/directives/findpatient.js, client/src/partials/sales/sales.html, client/src/partials/sales/sales.js, server/controllers/patient.js
This PR fixes #633 by implementing a new find-patient directive option: `init-lookup={uuid}`.  The find-patient directive listens for changes to this uuid and executes a search to `/patient/:uuid` when it changes.  This enables sale recovery to simply define the value as the old patient uuid, and that patient's information is loaded.
=> Enable programmatic find-patient search

gulpfile.js, package.json
Potentially fixes #669.  According to [this SO question](http://stackoverflow.com/questions/28885074/running-del-npm-dependency-from-package-json-script-on-windows), the `del` npm module might have errors on windows.  This PR uses `rimraf` instead.
=> use rimraf instead of del for windows

client/src/i18n/currency/fc.json, client/src/i18n/currency/usd.json, client/src/i18n/locale/angular-locale_en-us.js, client/src/i18n/locale/angular-locale_fr-be.js, client/src/i18n/locale/angular-locale_fr-cd.js, client/src/i18n/locale/angular-locale_fr-fr.js, client/src/i18n/locale/angular-locale_ln-cd.js, client/src/index.html, client/src/js/app.js, client/src/js/define.js, client/src/js/filters/currency.js, client/src/js/filters/filters.js, client/src/js/services/currencyFormat.js, client/src/partials/bhima/application.js, client/src/partials/receipts/receipt.sale.js, client/src/partials/receipts/templates/receipt_sale.html, client/src/partials/settings/settings.js, client/vendor/angular-dynamic-locale/tmhDynamicLocale.js, gulpfile.js, server/controllers/finance.js, server/models/development/update/synt.sql
Attempt 2.
In this PR:
1. Localisation using ngLocale, configures angular filters based on locale - the primary change has been updating dates from only US format to respecting the user language. __(Note: this does not apply to the currency filter - as described in this pull request)__
2. Forked the native angular currency filter - it is essential that currencies in BHIMA are __not__ dependent on locale, they must respect the original transactions currency. This filter enables:
* Safe alternative to intlcurrency, no html binding is used
* Filter independently of current locale
* Specifiy BHIMA currency ID to request formatting
* Render strong warnings if a non-supported currency is used or a mistake is made 
* Asynchronously filter based on available JSON configuration files
3. Updated …
=> Localisation and reworking currency

client/src/partials/cotisation/create/create_cotisation.html, client/src/partials/cotisation/create/create_cotisation.js
This PR fixes #683.  It cleans up the code slightly, allowing for fewer checks of data-types by enforcing existence and using 1/0 for checkbox true and false values.  The `<select>` statements for accounts have been optimized slightly.
Finally, it fixes a typo that prevented new cotisations from being created.
=> Fix cotisation creation

client/src/partials/reports/global_transaction/global_transaction.html, client/src/partials/reports/global_transaction/global_transaction.js
Using ng-options is **significantly** faster than using an ng-repeat on an <options> tag as discussed #701 and #700. 
This PR demonstrates this taking DOM load time from ~7 seconds to < 1 second. 
It also demonstrates the new ng-options API that allows the developer to specify when to disable options using the 'disable when' syntax 
```<select ng-options="account.displayString disable when (account.disabled) for account in accounts.data" ng-model="session.selectedAccount"></select>```
=> Demonstrating new ng-options tools

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/partials/receipts/receipt.purchase.js, client/src/partials/receipts/receipts.js, client/src/partials/receipts/templates/receipt_purchase.html
Purchase invoices were entirely broken due to an errant string.  This
string has been removed, as well as hard coded values in the purchase
template.  The following other changes have taken place:
1. Controller abides by Angular Style Guide Syntax.
2. Enterprise address uses <address> to be more semantic
3. Added <abbr> for abbreviations and associated translations
=> FIX: purchase invoices render properly

client/src/js/services/dateservice.js
The `DateService` can be required by any module and is meant to facilitate quick date calculates on the order of days, weeks, months, and years.  It can be leveraged for report modules to allow easy customization of date ranges.  An example range for a two week period 7 weeks ago might be:
```js
var range = {
start : DateService.previous.nWeek(9), // two week span between
end : DateService.previous.nWeek(7)    // 9 - 7 weeks ago
}
```
This service can be leveraged by the directive proposed by @sfount in #723 or directly from controllers.  It is particularly useful for dashboards and/or reports with predefined selections.  It could be leverage immediately to remove the redundancy from our Cash/Sale/Patient Records pages that use the "Today, This Week, This Month" drop downs.
Provided …
=> Feat(DateService) for quick date manipulation

client/src/js/app.js, client/src/partials/purchase/create/purchase.js, client/src/partials/purchase/view/purchase_records.html, client/src/partials/purchase/view/purchase_records.js, client/src/partials/purchase/view/purchase_view.html
For more clarty I introduced the new syntax for service injector as discussed,
In this PR, I corrected the error in purchase order page also
=> Fixing erros, Aliasing, new service injector Syntax

client/src/partials/stock/exit/distribution.html, client/src/partials/stock/exit/distribution.js, server/controllers/journal/distribution.js
In this PR we have fixed an error which was occurring when we try to distribute medecines to patient after a sale operation
=> Fixing patient distribution after a sale operation

client/src/partials/creditor/creditor.html
In this PR we have fixed label for an adress area in supplier management because when we try to edit a supplier we can't see that the address is required, and we cannot edit anything (the button is disabled).
=> Required label for address area in supplier management

.travis.yml, package.json
We now build the database within the .travis.yml file using travis's
root user on MySQL.  Unfortunately, since our build process is not well
established, we have to hard-code the user and password into the
.travis.yml.  See this file for suggestions on how to improve our build
process.
Also included: before running, we install gulp & bower globally and run bower
install.
=> FIX(travis): Make travis successfully build project

server/models/development/update/synt.sql, utilities/account/fixing_parent/fixingAccountParent.js
In this PR, we have wrote a script `fixingParentAccount.js` for fixing parent account, some account has like parent an account_number instead of an id of the account.
The script is in `/utilities/account/fixing_parent`, 
To run the script : 
```
cd /utilities/account/fixing_parent/
node fixingParentAccount.js
```
The process is finished when you see `Update parent with success...`
=> Fixing parent account

server/controllers/reports_proposed/data/grand_livre.js, server/controllers/reports_proposed/reports.js, server/controllers/reports_proposed/templates/grand_livre.dot
I've increased the rendering speed of the PDF report by migrating all
the sorting and grouping logic from JS to SQL.  This results in much
cleaner code (if you read SQL).
Additional fixes include:
- number formatting for debit/credit fields
- date now established at request time, rather than at first run time
NOTE
Trying to print the entire general ledger still results in a broken
(timed out) HTTP request.  We need to disallow printing a max number of
transactions/rows/dates to avoid needlessly hanging the server.
=> Perf(general ledger report): Faster PDF rendering

client/src/js/directives/findpatient.js, server/controllers/patient.js
I've updated the patient find directive to use strict matching on
first_name, last_name, middle_name.  We do all possible combinations of
matches (9 total) to ensure that we do not miss an data inserted in
incorrect order.
This commit also updates the find-patient directive to meet the styleguide
standards.
Fixes #708.
=> FIX(find-patient): remove SOUNDEX algorithm

package.json
This PR fixes a bug where `npm install` does not install all dependencies.  It now installs connect-multiparty at the latest version.
**Edit** Apparently `npm install` reorders items in the package.json.  The changes haven't changed the package versions though.  The only change in here is the addition of connect-multiparty.  All other packages retain their original versions.
=> Fix: Add connect-multiparty to package.json

client/src/partials/sales/sales.html, client/src/partials/sales/sales.js
This commit fixes several issues with recovering sales:
1. The invoice_date and is_distributable fields are now able to be
recovered with the rest of the sale.
2. The sale now saves to appcache when removing items as well as on
addition, ensuring that a working copy remains up to date with edits
3. Changed a form-control to a form-bhima.
Fixes #318.
=> FIX(sales): improved sale recoverability

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/js/app.js, client/src/partials/group_invoice/group_invoice.html, client/src/partials/group_invoice/group_invoice.js, client/src/partials/journal/journal.utilities.js
This PR rewrites the client-side code base of Group Invoice (`/group_invoice`), but does not change the logic.  The following changes have been made:
- No more UUIDs in the view
- All currency filters reference the sale currency ID
- Complete removal of `$scope` in favor of `controller as` syntax
- Loading indicators while data is fetched from the server
- Fixes to broken HTML.
Fixes #674.
=> Rewrite Group Invoice

server/config/environment/server.js, server/config/express.js
This commit stops the server from deleting sessions from the file store.
That means a user must explicitly log out to remove their session
information (or the server must be restarted).
If we have better login error handling and messaging, this can be reset.
At the moment, it's very helpful so that users do not get kicked out of
their sessions while working.
=> FIX(sessions): Allow persistent sessions

client/src/partials/exchange_rate/exchange_rate.html, client/src/partials/exchange_rate/exchange_rate.js
This commit fixes a critical bug in which the rates were always set to
the day before.  This is do to errors in the angular validation,
stemming from differences between ngMax and the HTML max attribute.
Fixes #824.
=> FIX(exchange): set rates to today, not yesterday

client/src/index.html
Since we have agreed to use Controller.$inject syntax (#719), and are compiling
all our scripts through gulp, we can get some speed gains by adding the
strict DI mode directive to the main application.  For more details,
[see this link](https://docs.angularjs.org/guide/production).
I've tested most of the modules, and this change leaves them unaffected.
However, if we do find issues, we might want to add ng-annotate to our
gulp build.
=> FEAT(di): require strict dependency injection

client/src/partials/reports/stock_status/stock_status.html, client/src/partials/reports/stock_status/stock_status.js
This commit removes the dependence on the fixed inventory numbers and
shows only the projected numbers from stock calculations over time.
NOTE that is change is hard-coded, and needs to provide more flexibility
to the users viewing the stock status report than it is able to provide
here.
Finally, the alert column is hidden in the printed form.
=> CHORE(stock status): display stock projections

client/src/partials/inventory/groups/groups.html, client/src/partials/inventory/groups/groups.js
This commit replaces old ng-repeats with ng-options for speed gains.
Creating and editing inventory groups is now much faster.
Fixes #854.
=> FIX(inventory group): severe UI lag reduced

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/partials/journal/trialbalance/trialbalance.html
This commit changes the way error and results states work in the trial
balance.  Rather than having a single button with the message "view errors",
and is toggled _active_ when clicked, we now change the button text
depending on the current state.  While looking at results, it will still
read "view errors", but will switch to "view results" on click to
clearly indicate to the user to return.
**Results Mode**
**Error Mode**
=> FIX(trial balance): separate balance states

client/src/partials/journal/journal.grid.js, client/src/partials/journal/journal.utilities.js
Fixes #842.
This commit re-renders the grid through a call to `grid.invalidate()`
whenever the session.mode changes, rather than regrouping.  This has
the affect of ensuring that the edit mode buttons are present when the
user needs them.
=> FIX(journal): grid edit mode renders properly

client/src/index.html, client/src/partials/primary_cash/expense/generic.html, client/src/partials/primary_cash/expense/generic.js, client/src/partials/primary_cash/income/generic/generic.html, client/src/partials/primary_cash/income/generic/generic.js
Fixes #849.
This commit fixes the date limits in both the generic expense and
generic income forms.  Previously, the min/max attributes limited the
date selection to all dates including the next day, this commit changes
that selection to all dates including the present day.
Other minor changes:
- $scope.$watch() --> $scope.$watchCollection() for collections
- Nicer JS formatting
=> FIX(primary cash): ui date form limits

client/src/index.html, client/src/js/app.js, client/src/partials/primary_cash/expense/cash_return.html, client/src/partials/primary_cash/expense/cash_return.js
Fixes #711.
This commit ensures that the user cannot submit the cash reimbursement
form without first selecting a currency id.  Additionally, it uses form
`<label>` elements instead of input groups render to form, to be more in
line with bhima's style so far.  Finally, the HTML has been cleaned up a fair amount.
=> FIX(cash return): do not submit w/o currency

client/src/partials/primary_cash/primary.html
This commit removes the thumbs-up and thumbs-down glyphicons from the
primary cash interface.  They originally were a joke by @sfount, but
seemed to have persisted into production.  They have been replaced by
import/export type icons which do not have the same significance as the
previous set.
=> FIX(primary cash): remove thumb icons in interface

gulpfile.js
This commit creates the options available for JavaScript minification in
production.  The options here have been tested, and reduce the bhima script
size by more than 50%.
Additionally, the order of IIFE has been change so that a single IIFE
wraps the entire bhima script, rather than multiple created for each
bhima javascript file.  This should produce smaller file sizes and
slight performance improvements.
**NOTE**: The minification option is still turned off in this commit.  It should be turned on in production.
=> CHORE(build): ensure js minification works

client/src/js/app.js, client/src/partials/cost_center/allocation/allocation.css, client/src/partials/cost_center/allocation/allocation.html, client/src/partials/cost_center/allocation/allocation.js, client/src/partials/cost_center/assigning/assigning.css, client/src/partials/cost_center/assigning/assigning.html, client/src/partials/cost_center/assigning/assigning.js, client/src/partials/cost_center/center/analysis_center.css, client/src/partials/cost_center/center/analysis_center.html, client/src/partials/cost_center/cost_center.html, client/src/partials/cost_center/cost_center.js
This commit fixes lots of HTML + CSS in all cost center modules.  Some
notable changes:
1. Use "clearfix" to handle content overflows instead of fixed heights
in pixels.
2. Force tables to adopt a fixed height and scroll-y on overflow
3. Use proper bootstrap styles for form groups, labels, and static
content
4. Use class="extend" to remove white footer
5. Translations implemented for cost_allocations
6. Use ng-options instead of ng-repeat for speed improvements and allow
a default SELECT option
7. Loading indicators moved into table and "no data" messages do
not show until data finished loading (#726).
8. Currencies are rendered with enterprise currency id
9. Currencies are right-aligned
10. Removed unused CSS files
**Screenshots**
=> CHORE(cost center): structure/style improvments

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/partials/journal/journal.controls.js, client/src/partials/journal/journal.utilities.js
Fixes #702.
This commit prevents the journal from throwing and error when an account
is missing (in error) and the user selected 'group by account'.
Instead, the missing account(s) will be labeled 'Unknown Account', and
be grouped at the top of the posting journal.
=> FIX(journal): show errors for missing accounts

client/src/partials/primary_cash/expense/multi_payroll.js
Fixes #680.
This commit fixes a poorly designed promise chain that would swallow
both serverside and client side errors.  This commit requires that all
HTTP requests complete before reporting success or failure.
=> FIX(payroll): ensure client reports errors

client/src/css/report.css, client/src/i18n/en.json, client/src/partials/reports/global_transaction/global_transaction.html, client/src/partials/reports/global_transaction/global_transaction.js, client/src/partials/reports/operating_account/operating_account.html, client/src/partials/reports/operating_account/operating_account.js, client/src/partials/reports/transactions/account.html, client/src/partials/reports/transactions/account.js, client/src/partials/reports_proposed/balance/balance.html, client/src/partials/reports_proposed/balance/balance.js, server/controllers/report.js
This commit implements a number of fixes on accounting reports.  They
are enumerated here:
1. Massive HTML cleanups.  Make sure labels line up with inputs, using
ng-options where possible, etc.
2. Broken conversion to `controller as` in operating_account has been
corrected.
3. Better translations in places
4. Make sure reports that overflow are visible about footers
5. Make sure currencies are right-aligned and formatted with their
proper currency ids.
**NOTE** This commit does not change _anything_ about the behavior of the accounting reports, except where the report was broken and has been fixed.  Behavioral changes will follow in a separate pull request.
=> CHORE(reports): clean up reports

gulpfile.js
This pull request speed up the client build process significantly. 
On my development machine the build process now takes **~900ms** down from **~7s**. 
The client lint process has been moved to a new task **gulp lint**. A warning has been added to the build process to remind developers to lint their code before submitting a pull request. This utilises gulp-util (developed by the gulp team).
=> Removed client lint from client build process 

server/controllers/inventory.js, server/controllers/inventory/lots.js, server/controllers/inventory/stock.js
This commit fixes a critical bug where stock levels were only given if
stock was being consumed.  This has been corrected to include stock with
no consumption events.
=> FIX(inventory): calculate stock levels correctly

client/src/i18n/en.json, client/src/i18n/fr.json, client/src/partials/cotisation/create/create_cotisation.html, client/src/partials/taxe/create/create_taxe.html
This PR fix the `four` and `six` account labels in cotisations and tax management by replacing them by `account to credit` and `account to debit`
=> Fixing tax and cotisation labels

client/src/partials/receipts/receipt.service_distribution.js, client/src/partials/receipts/templates/receipt_service_distribution.html, client/src/partials/stock/exit_service/distribution_service.html, client/src/partials/stock/exit_service/distribution_service.js
This PR fix the distribution to the service
=> Fixing service distribution

client/src/partials/stock/service_return_stock/service_return_stock.js
This PR fixes the `Return distribution from service` module. 
To run correctly the app, please : 
- Don't use `STRICT_ALL_TABLES` mysql mode 
- Use the external file db.sql
- Then execute the /server/models/update/synt.sql file
NOTA: The exchange rate module doesn't have a bug when we try to define a new exchange rate when we are not in `STRICT_ALL_TABLES` mysql mode
=> Fixing select service in return medecines module
