IMA-WorldHealth/bhima-1.X

- client/src/partials/patient_registration/patient.html
Fixed errors in the 'Street' field in patient registration (wrong column name and input type).
> Fix patient registraton street input field

- server/controllers/report.js
- server/controllers/reports_proposed/config.js
- server/controllers/reports_proposed/data/balance.js
- server/controllers/reports_proposed/data/balance_sheet.js
- server/controllers/reports_proposed/reports.js
- server/controllers/reports_proposed/templates/balance_sheet.dot
- server/controllers/reports_proposed/templates/invoice.dot
- server/controllers/reports_proposed/templates/style/normalize.css
- server/controllers/reports_proposed/templates/style/reports.css
- server/controllers/reports_proposed/templates/style/skeleton.css
Generic proposal for creating well formed reports. This pull request combines the basic balance sheet context with a template for PDF generation.
> Balance Sheet - Report Templating

- client/src/partials/reports/chart_of_accounts/chart.js
This PR fixes a display issue with the CoA report.
> FIX: chart of accounts referenced by id, not account_number

- server/models/stock.sql
In this PR:
- Update the stock.sql file to define default configuration values for payroll test
> Sql for payroll default data configuration

- client/src/partials/accounts/create_account/create.js
Remove the possibility to edit an account
> Remove the possibility to edit an account

- client/src/js/directives/tree.js
- client/src/partials/bhima/application.js
- client/src/partials/bhima/tree.js
- server/controllers/tree.js
This PR orders the nodes in the tree alphabetically by their translated language.  Resorts on language change.
> Order tree nodes alphabetically, in any language

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/purchase/confirm/confirm.html
- client/src/partials/purchase/purchase_menu.js
- server/models/base.sql
Adding confirm purchase orders in the tree of bhima and removal it in the Purchase Orders Management Menu
> Confirm p orders

- server/models/stock.sql
In this PR:
- Remove the `closing_account` column entry in stock.sql
> Fixing stock.sql

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/patient_edit/edit_patient.html
- client/src/partials/patient_edit/edit_patient.js
- client/src/partials/patient_registration/patient.html
- server/models/bhima.sql
- server/models/updates/2015-01-12-add-patient-notes.sql
Although I added 'notes' to the patient table in bhima.sql, I did not regenerate base.sql with 'NULL's for this missing field in the patient data.  If anyone needs to reload bhima.sql and base.sql follow this procedure:
* Temporarily comment out the line for 'notes' in the 'patient' table definition in bhima.sql
* Load bhima.sql and base.sql
* Restore bhima.sql
* Execute the sql update script:  server/models/2015-01-12-add-patient-notes.sql
> Add 'notes' field to patient

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/directives/findpatient.js
- client/src/partials/patient_edit/edit_patient.html
- client/src/partials/reports/account_statement/account_statement.html
- client/src/partials/templates/findpatient.tmpl.html
Cleaned up translation items for the find patient directive: Removed unused ones, renamed some keys to better reflect the functionality, and removed duplicate items
Minor fixes to make it operate more cleanly in both the swap_debtor and patient_edit pages.
> Updates for find patient directive

- client/src/i18n/fr.json
- client/src/partials/reports/global_transaction/global_transaction.html
- client/src/partials/reports/global_transaction/global_transaction.js
- server/controllers/report.js
Fix report : Transactions states by account
> Fixglobal transactions

- client/src/partials/user_permission/permissions.html
- client/src/partials/user_permission/permissions.js
Sort all unit items alphabetically
> Sort all unit items alphabetically

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/sales/sales.html
- client/src/partials/subsidy/subsidy.html
In this PR : 
- Fixing translate in Subsidy Management
- Fixing label in Finance/Sales
> Fixing translate in subsidy and sale

- client/src/partials/receipts/receipt.sale.js
- client/src/partials/receipts/templates/receipt_sale.html
Fix: Currencies changing error
> Fix: Currencies changing error

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/directives/findaccount.js
- client/src/js/directives/findaccount.md
- client/src/partials/reports/account_statement/account_statement.html
- client/src/partials/reports/account_statement/account_statement.js
- client/src/partials/templates/findaccount.tmpl.html
Created a new findAccount directive.
Updated the Report/Account Statement page to use the new directive.
I've added several options to the findAccount directive that should make it more useful in various contexts.  I addeda  documentation page in the client/src/js/directives folder:
[findaccount.md](https://github.com/jmcameron/bhima/blob/feature/find_account_directive/client/src/js/directives/findaccount.md)
> Created new find account directive

- client/src/css/bhima.css
- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/budget/budget.html
- client/src/partials/budget/budget.js
- server/config/routes.js
- server/controllers/csv.js
- server/controllers/uncategorised.js
Added a new page to create and edit budget data for individual accounts for a specific fiscal year.
WARNING: This addition requires adding a new database entry. You can do that using this file:
server/models/updates/2015-01-13-Add-budget-edit-menu.sql
NOTE: The English versions of the translation items have been copied to the fr.json file but have not been translated. I've appended a '???' on the untranslated items. I request help from @DedrickEnc or @mbayopanda or @lomamech with the translations. Feel free to email them to me and I'll update the pull request.
This is a redirect of PR https://github.com/IMA-WorldHealth/bhima/pull/340 against development.
> Added page to create/edit budgets

- server/models/base.sql
In this PR : 
- We move 'General ledger' from 'Reports' to 'Accounting/'
> Moving General Ledger to Accounting

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/reports/distribution_record/distribution_record.html
- client/src/partials/reports/distribution_record/distribution_record.js
- client/src/partials/reports/distribution_record/distribution_record_view.html
- client/src/partials/reports/distribution_record/distribution_record_view.js
- client/src/partials/reports/distribution_service_record/distribution_service_record.html
- client/src/partials/reports/distribution_service_record/distribution_service_record.js
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.html
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.js
- client/src/partials/reports/loss_record/loss_record.css
- client/src/partials/reports/loss_record/loss_record.html
- client/src/partials/reports/loss_record/loss_record.js
- client/src/partials/stock/distribution_record/distribution_record.html
- client/src/partials/stock/stock.js
- server/models/base.sql
Harmonization of interfaces of the stock modules and some reports
> Harmonisation of interfaces of the stock modules and some reports

- client/src/css/bhima.css
- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/budget/budget.css
- client/src/partials/budget/budget.html
- client/src/partials/budget/budget.js
- client/src/partials/budget/edit/edit_budget.html
- client/src/partials/templates/findaccount.tmpl.html
Fixed issues outlined by Jonathan Niles on slack.
See: https://bhima.slack.com/archives/general/p1422407025000002
> Fixed various issues with budget/balance page

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.html
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.js
In this PR : 
- We have added an interface for configuring a service distribution report
> Report config for service distribution

- client/src/partials/reports/distribution_record/distribution_record_view.html
- client/src/partials/reports/distribution_record/distribution_record_view.js
In this PR : 
- We have added an interface for configuration patient distribution report
> Report config for patient distribution

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/global_transaction/global_transaction.html
- client/src/partials/reports/global_transaction/global_transaction.js
In this PR : 
- We have added an interface for configuring the global transaction report
> Report config for global transactions

- client/src/js/app.js
- client/src/partials/reports_proposed/balance/balance.html
- client/src/partials/reports_proposed/balance/balance.js
- server/controllers/reports_proposed/data/old_balance_sheet
- server/controllers/reports_proposed/templates/balance_sheet.dot
- server/controllers/reports_proposed/templates/exemple_aaray.dot
- server/models/base.sql
In this PR, we created a set of user interface to generate the balance sheet report.
> implementing balance sheet continues

- server/models/updates/2015-01-29-update-accounts.sql
In this PR : 
- We create a sql file '2015-01-29-update-accounts.sql' for : 
+ insert missing parent entry in account table
+ update depending accounts according the new parent entry
+ update the is_asset column in account
> Update account parent and is_asset

- client/src/partials/reports/transaction_report/transaction_report.html
It looks like transaction_report is incomplete, but I fixed this CSS item anyway.
> Changed 'hide-print' to the recently added 'no-print' CSS rule

- server/models/updates/2015-01-29-update-accounts.sql
In this PR : 
- We have fixed some account parent class
- We set to NULL all account which have parent=0
> Update accounts class parent

- server/models/updates/2015-01-29-update-accounts.sql
In this PR : 
- We update the account_txt to UPPER(account_txt) for one and two digits account class
> Uppercase account_txt for one and two digits class account

- client/src/partials/reports/employee_standing/employee_standing.html
- client/src/partials/reports/employee_standing/employee_standing.js
- client/src/partials/reports/payroll_report/payroll_report.js
Update interface of report Employee Standing and other fixes
> Update interface of report Employee Standing and other fixes

- client/src/partials/reports/patient_registrations/patient_registrations.html
- client/src/partials/reports/patient_registrations/patient_registrations.js
In this PR : 
- We have fixed some ui code in report/patient_registration
> Report config for patient

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/enterprise/enterprise.html
- client/src/partials/enterprise/enterprise.js
- client/src/partials/receipts/receipts.js
- client/src/partials/receipts/templates/confirm.purchase.html
- client/src/partials/receipts/templates/confirm_direct.purchase.html
- client/src/partials/receipts/templates/consumption.html
- client/src/partials/receipts/templates/receipt_confirm_direct_purchase.html
- client/src/partials/receipts/templates/receipt_confirm_indirect_purchase.html
- client/src/partials/receipts/templates/receipt_consumption.html
- client/src/partials/receipts/templates/receipt_convention.html
- client/src/partials/receipts/templates/receipt_cotisation_paiement.html
- client/src/partials/receipts/templates/receipt_generic_expense.html
- client/src/partials/receipts/templates/receipt_generic_income.html
- client/src/partials/receipts/templates/receipt_indirect_purchase.html
- client/src/partials/receipts/templates/receipt_loss.html
- client/src/partials/receipts/templates/receipt_payroll.html
- client/src/partials/receipts/templates/receipt_payslip.html
- client/src/partials/receipts/templates/receipt_purchase.html
- client/src/partials/receipts/templates/receipt_sale.html
- client/src/partials/receipts/templates/receipt_service_distribution.html
- client/src/partials/receipts/templates/receipt_tax_payment.html
- client/src/partials/receipts/templates/receipt_transfer.html
- client/src/partials/receipts/templates/sale.html
- server/models/bhima.sql
- server/models/updates/2015-02-03-enterprise-updates.sql
Add a colums po_box in bhima.sql for the table enterprise and update all receip
> Add a colums po_box in bhima.sql for the table enterprise and update all receip

- client/src/partials/reports/patient_registrations/patient_registrations.html
sanitaze of form of patient registraction report
> sanitaze of form of patient registraction report

- client/src/partials/reports/account_statement/account_statement.html
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.html
- client/src/partials/reports/cash_payments/cash_payments.html
- client/src/partials/reports/chart_of_accounts/chart.html
- client/src/partials/reports/daily_consumption/daily_consumption.html
- client/src/partials/reports/distribution_record/distribution_record_view.html
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.html
- client/src/partials/reports/employee_standing/employee_standing.html
- client/src/partials/reports/expiring_stock/expiring_stock.html
- client/src/partials/reports/expiring_stock/expiring_stock_view.html
- client/src/partials/reports/finance/finance_report.html
- client/src/partials/reports/global_transaction/global_transaction.html
- client/src/partials/reports/income_expensive/income_expensive.html
- client/src/partials/reports/loss_record/loss_record.html
- client/src/partials/reports/operating_account/operating_account.html
- client/src/partials/reports/patient_group/patient_group.html
- client/src/partials/reports/patient_registrations/patient_registrations.html
- client/src/partials/reports/patient_standing/patient_standing.html
- client/src/partials/reports/payroll_report/payroll_report.html
- client/src/partials/reports/prices/prices.html
- client/src/partials/reports/primary_cash/expense/expense_report.html
- client/src/partials/reports/primary_cash/income/income_report.html
- client/src/partials/reports/service_exploitation/service_exploitation.css
- client/src/partials/reports/service_exploitation/service_exploitation.html
- client/src/partials/reports/stock/stock_report.html
- client/src/partials/reports/stock_status/stock_status.html
- client/src/partials/reports/templates/enterprise_header.html
- client/src/partials/reports/templates/enterprise_header.js
- client/src/partials/reports/transaction_report/transaction_report.html
- client/src/partials/reports/transactions/account.html
In this PR : 
- We have created header template and controller in 'partials/reports/templates/'
- We have added header in reports
- Fixing patient registration config report ui
> Enterprise header in reports

- client/src/partials/primary_cash/expense/partial_payment.js
> fixing jshint error in partial_payment

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/subsidy/subsidy.html
In this PR : 
- We have fixed translate in subsidy and in others modules
> Fixing translate in BHIMA

- client/src/partials/templates/findaccount.tmpl.html
Restoration of buttom submit for the directive found account
> Restoration of buttom submit for the directive found account

- client/src/partials/reports/account_statement/account_statement.html
- client/src/partials/reports/cash_payments/cash_payments.html
In this PR : 
- we have fixed ui in some reports
> Fixing report ui

- client/src/partials/primary_cash/expense/multi_payroll.html
- client/src/partials/primary_cash/expense/multi_payroll.js
- client/src/partials/reports/cash_payments/cash_payments.html
Sort employee list for main interface of payroll
> Sort employee list for main interface of payroll

- client/src/partials/primary_cash/income/transfer/transfer.js
- client/src/partials/receipts/receipts.js
Fix error of link on generic income for /transfert
> Fix error of link on generic income for /transfert

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/cash_payments/cash_payments.html
- client/src/partials/reports/loss_record/loss_record.html
- client/src/partials/reports/operating_account/operating_account.html
- client/src/partials/reports/patient_registrations/patient_registrations.html
- client/src/partials/reports/primary_cash/expense/expense_report.html
- client/src/partials/reports/primary_cash/income/income_report.html
- client/src/partials/reports/transactions/account.html
- client/src/partials/reports/transactions/account.js
Adding footer on reports for the printer
> Adding footer on reports for the printer

- server/controllers/report.js
Update request for employee standing
> Update request for employee standing

- server/models/updates/2015-02-20-depot-updates.sql
Adding sql file for update table depot with colums  is_warehouse
> Adding sql file for update table depot with colums  is_warehouse

- client/src/partials/price_list/pricelist.css
- client/src/partials/price_list/pricelist.html
In this PR : 
- Fxing css in 'Admin/Price list' when selecting an item
> Fixing price list css

- server/controllers/journal.js
In This PR, we have : 
- Fixed description for a rounding exchange rate in 'journal.js' for a cash payment
> Fixing rounding exchange rate

- client/src/js/services/stockControler.js
- client/src/partials/reports/stock_status/stock_status.html
- client/src/partials/reports/stock_status/stock_status.js
- Clean the code in 'stock_status.js' and in 'stockControler.js'
- Fixed the problem of values which change (stock_months and Quantity_to_order) in stock_status
> Fixing stock status values

- client/src/partials/stock/donation_management/donation_management.html
In this PR : 
- We change the purchase_price field of a donation to an editable field
> Donation editable purchase_price field

- client/src/partials/user_permission/permissions.html
In this PR : 
- We have added a title when choosing a user for a permission units update
> Fixing user permission ui

- client/src/partials/home/home.js
- client/src/partials/inventory/inventory.js
- server/middleware/authentication.js
In this PR 
Authentication, home page and inventory home page are fixed
> Minors fixes

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/creditor/group/creditor_group.html
- client/src/partials/fonction/fonction.html
- client/src/partials/grade_employers/grade_employers.html
- client/src/partials/inventory/register/register.js
- client/src/partials/journal_voucher/journal_voucher.js
- client/src/partials/primary_cash/expense/generic.js
- client/src/partials/primary_cash/income/generic/generic.js
- client/src/partials/purchase/create/purchase.js
- client/src/partials/sales/sales.js
- client/src/partials/stock/donation_management/donation_management.js
- client/src/partials/stock/exit/distribution.html
- client/src/partials/stock/exit_service/distribution_service.html
- client/src/partials/stock/movement/movement.html
- client/src/partials/stock/stock.js
Correction requettes allowing selection of inventories, filtering lists by alphabetic order, improvement of translation and other fixing
> Correct purchase

- client/src/partials/employee/employee.html
- Fixed an html file of emplyee when there are not employees in the system
> Fixing employee table list if empty

- client/src/partials/primary_cash/expense/purchase.js
- client/src/partials/purchase/confirm/confirm.js
- client/src/partials/purchase/view/purchase_records.html
- client/src/partials/purchase/view/purchase_records.js
- client/src/partials/purchase/view/purchase_view.html
- client/src/partials/purchase/view/purchase_view.js
- client/src/partials/stock/donation_management/donation_management.html
- client/src/partials/stock/donation_management/donation_management.js
- client/src/partials/stock/exit/distribution.js
- client/src/partials/stock/loss/loss.js
- server/controllers/journal.js
- server/controllers/uncategorised.js
- server/models/updates/synt.sql
In this PR, we : 
- Tracking a purchase_price for a donation
- Simulate a purchase for a donation for distribution
- Fixing dashboard values for purchase
- Fixing handleDonation in journal.js 
- Add and edit some entries in "synt.js" relatives to purchase
> Donation management and stock dashboard fixing

- client/src/partials/stock/exit/distribution.js
- server/controllers/journal.js
- server/models/updates/synt.sql
In this PR, we implemented a : 
- rollback when error occur in patient distribution
> Handle patient distribution errors in journal.js

- server/controllers/journal.js
In this PR, we handled errors when distributing to service
> Handle service distribution errors in journal.js

- server/controllers/journal.js
In this PR, we implemented a rollback when error occur in stock loss operation (in journal.js)
> Handle stock loss error

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/fiscal/fiscal.create.js
- server/controllers/fiscal.js
- server/controllers/journal.js
- make that new fiscal_year write to the journal instead of period_total
> Posting new fiscal year balance to journal

- client/src/partials/receipts/receipt.cash.js
- client/src/partials/receipts/templates/receipt_cash.html
- Fixed currency conversion in cash receipt
> Fixing conversion in cash receipt

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/receipts/receipt.cash_discard.js
- client/src/partials/receipts/receipts.js
- client/src/partials/receipts/templates/receipt_cash_discard.html
- added a receipt for cash discared
- fixed translation
> Receipt of cash discared

- client/src/js/app.js
- client/src/partials/primary_cash/expense/cash_return.html
- client/src/partials/primary_cash/expense/cash_return.js
- client/src/partials/primary_cash/primary.js
- server/controllers/journal.js
- server/models/updates/synt.sql
I finished cash return implementation, translation and receipt remain
> cash return inplementation done

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/primary_cash/expense/cash_return.html
- client/src/partials/primary_cash/expense/cash_return.js
- client/src/partials/receipts/receipt.cash_return.js
- client/src/partials/receipts/receipts.js
- client/src/partials/receipts/templates/receipt_cash_return.html
In this PR : 
we have added a recipt for cash return and fixing ui
> Receipt in cash return and fixing ui

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/cash_discard/cash_discard.js
- client/src/partials/caution/caution.js
- client/src/partials/receipts/receipt.caution.js
- client/src/partials/receipts/templates/receipt_caution.html
- client/src/partials/records/auxillary_cash_records/auxillary_cash_records.html
- client/src/partials/records/auxillary_cash_records/auxillary_cash_recors.js
- server/controllers/report.js
- server/models/updates/synt.sql
- Fixed caution receipt in auxillary cash record
- Fixed caution cancellation
> Handling Caution receipt and cancellation

- client/src/partials/reports/patient_standing/patient_standing.html
- server/controllers/report.js
- Fixed the function patientStanding() in report.js
- Fixed patient standing ui
> Fixing patient standing report

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/credit_note/credit_note.html
- client/src/partials/credit_note/credit_note.js
- client/src/partials/stock/reversing_distribution/reversing_distribution.js
Condition the cancellation of a sale if the sale has not consumed or if it's not paid, for that il will be firstly cancel the sale or consumption
> Condition the cancellation of a sale

- server/controllers/report.js
update sql request using the table caution
> update sql request using the table caution

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/cotisation/config_cotisation/config_cotisation.js
- client/src/partials/group_invoice/group_invoice.js
- client/src/partials/inventory/register/register.js
- client/src/partials/journal/journal.controls.js
- client/src/partials/patient_group/patient_group.js
- client/src/partials/patient_group_assignment/patient_group_assign.js
- client/src/partials/primary_cash/expense/multi_payroll.js
- client/src/partials/stock/donation_management/donation_management.js
- client/src/partials/support/support.js
little fix around translation and more
> little fix around translation and more

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/purchase/create/purchase.js
Prevent a purchase order if the purchase price is not defined
> Prevent a purchase order if the purchase price is not defined

- client/src/partials/cost_center/assigning/assigning.html
- client/src/partials/cost_center/center/analysis_center.html
- client/src/partials/location/location.html
- client/src/partials/patient_group/patient_group.html
- client/src/partials/price_list/pricelist.html
- client/src/partials/profit_center/center/analysis_profit_center.html
- client/src/partials/service/service.html
- client/src/partials/subsidy/subsidy.html
- server/controllers/location.js
Ordering of lists in alphabetical order
> Ordering of lists in alphabetical order

- client/src/partials/patient_group/patient_group.html
- server/controllers/reports/patient_group.js
- Fixed patient group when there is a click on patient group which  doesn't have a price list
> Fixing patient group error due to missing price list

- client/src/partials/debtor/debtor_group.html
We have removed a Max Credit input
> Fixing debitor group ui

- client/src/partials/receipts/templates/receipt_indirect_purchase.html
> Fix invoice Purchase Orders

- client/src/partials/sales/sales.js
In this PR, we have fixed eronous total value in sale (sale.js)
> Fixing eronous total value in sale

- client/src/i18n/fr.json
- client/src/partials/reports/account_statement/account_statement.html
- client/src/partials/reports/distribution_record/distribution_record_view.html
- client/src/partials/reports/distribution_record/distribution_record_view.js
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.html
- client/src/partials/reports/distribution_service_record/distribution_service_record_view.js
- client/src/partials/reports/loss_record/loss_record.html
- client/src/partials/reports/primary_cash/income/income_report.html
- client/src/partials/reports/service_exploitation/service_exploitation.html
- client/src/partials/reports/service_exploitation/service_exploitation.js
- Add the project selected in the header of service exploitation report
- Adding property required on interface for select store in report of records distribution
- Remove unused footer in report of account and Removing tracking numbers
> Fix report

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/stock/donation_management/confirm_donation.js
In this PR, we write donation in journal when confirmation
> Donation confirmation in journal

- client/src/partials/stock/donation_management/donation_management.js
- client/src/partials/stock/entry/start.js
Prevent Entry in stock of expired drugs
> Prevent Entry in stock of expired drugs

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/receipts/receipt_confirm_donation.js
- client/src/partials/receipts/receipts.js
- client/src/partials/receipts/templates/receipt_confirm_donation.html
- client/src/partials/reports/donation_confirmation/donation_confirmation.html
- client/src/partials/reports/donation_confirmation/donation_confirmation.js
- client/src/partials/stock/donation_management/confirm_donation.html
- client/src/partials/stock/donation_management/confirm_donation.js
- server/controllers/report.js
- server/models/updates/synt.sql
Creation receipt confirmation donation
Adding Report of confirmation Donation
> Receipt confirmation donation

- server/test/guid.spec.js
In this PR, I've added a few simple tests for guid.js to ensure uniqueness and correctness.
Addresses the issues brought up in #306.
> Server Tests: Guid.js

- server/lib/store.js
- server/test/store.spec.js
In this PR, I've added a few tests for store.js.  The beforeEach() hooks for mocha do not seem to be working, so once we figure that out, we could polish these tests a bit more.  For now, this will suffice.
Partially addresses #306
> Server Tests: Store.js

- client/src/partials/inventory/groups/groups.js
Update Inventory group for allowing empty accounts
> Update Inventory group for allowing empty accounts

- server/controllers/journal.js
Adding new transaction for transfer between cash_box and primary_cash
> Adding new transaction for transfer between cash_box and primary_cash

- client/src/css/report.css
- client/src/partials/reports/chart_of_accounts/chart.html
- client/src/partials/reports/chart_of_accounts/chart.js
In this PR we have fixed font-weight for account having title type
> Fixing bold for title

- client/src/partials/accounts/create_account/create.html
- server/controllers/uncategorised.js
In this PR, we have updated versement and accounting
> Update versement and accounting

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/creditor/group/creditor_group.js
- client/src/partials/debtor/debtor_group.js
- client/src/partials/patient_registration/patient.js
- client/src/partials/receipts/templates/receipt_patient.html
- server/controllers/uncategorised.js
- Added the support of only ohada account in creditor_group and debitor_group management
- Adding a machanism to forbid a duplication of a patient according his hospital_number ('hospital_no')
> Updates creditor_group, debitor_group, patient_registration

- client/src/partials/patient_registration/patient.js
In this PR we have fixed the zero file number when register a patient
> Fixing zero file_number

- client/src/js/app.js
Confirmation of a stock integration
> Stock confirmation integration ui display

- client/src/partials/inventory/update_item/update_item.html
Sort inventory list for form of inventory/update
> Sort inventory list for form of inventory/update

- client/src/partials/records/auxillary_cash_records/auxillary_cash_records.html
- client/src/partials/records/auxillary_cash_records/auxillary_cash_recors.js
- client/src/partials/records/sales_records/sales_records.html
- client/src/partials/records/sales_records/sales_records.js
Update report of sale record and auxillary cash report
> Update report of sale record and auxillary cash report

- client/src/partials/cash/extra_payment/extra_payment.js
- client/src/partials/records/auxillary_cash_records/auxillary_cash_recors.js
- server/controllers/journal.js
Sanitaze, fix error and improvent request in Journal JS
> Sanitaze, fix error and improvent request in Journal JS

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/reports/stock_store/stock_store.html
- client/src/partials/reports/stock_store/stock_store.js
- client/src/partials/stock/stock.js
- server/controllers/report.js
Report stock status by store and other fixes
> Stock level by store

- client/src/i18n/fr.json
Update the title of cash receipt in french
> Update the title of cash receipt in french

- client/src/partials/stock/integration/integration.js
> Improve alert text

- client/src/partials/accounts/create_account/create.html
- client/src/partials/accounts/create_account/create.js
> Improve management of account

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/records/auxillary_cash_records/auxillary_cash_records.html
- client/src/partials/records/auxillary_cash_records/auxillary_cash_recors.js
- client/src/partials/records/sales_records/sales_records.html
- client/src/partials/records/sales_records/sales_records.js
- client/src/partials/reports/stock_movement/stock_movement.js
- client/src/partials/reports/stock_store/stock_store.js
- server/controllers/report.js
Allow report of sale regristration and cash paiement by User
> Allow report of sale regristration and cash paiement by User

- client/src/partials/receipts/templates/receipt_sale.html
- client/src/partials/reports/patient_standing/patient_standing.js
- server/controllers/report.js
Improve invoice caution advance and report Patient Standing
> Improve invoice caution advance

- client/src/partials/cotisation/config_cotisation/config_cotisation.js
- client/src/partials/credit_note/credit_note.js
- client/src/partials/creditor/creditor.js
- client/src/partials/journal/journal.utilities.js
- client/src/partials/offdays/offdays.js
- client/src/partials/reports/patient_group/patient_group.js
- client/src/partials/subsidy/subsidy.js
- client/src/partials/user_permission/permissions.js
- server/app.js
- server/config/routes.js
- server/controllers/consumptionLoss.js
- server/lib/db.js
- server/lib/set.js
- server/middleware/authentication.js
- server/middleware/authorization.js
- server/middleware/projects.js
- server/test/set.spec.js
In this PR:
- Legacy `console.log()`s cleaned up
- middleware routes all use `db.exec()` for escapes
- various comments; formatting
- Set.js initialization and tests written
> Code cleanup/general

- client/src/partials/cotisation/create/create_cotisation.html
- client/src/partials/cotisation/create/create_cotisation.js
- client/src/partials/primary_cash/expense/cotisation_payment.js
- client/src/partials/primary_cash/expense/enterprise_tax_payment.js
- client/src/partials/primary_cash/expense/multi_payroll.js
- client/src/partials/primary_cash/expense/partial_payment.js
- client/src/partials/primary_cash/expense/purchase.js
- client/src/partials/primary_cash/expense/salary_payment.js
- client/src/partials/primary_cash/expense/tax_payment.js
- client/src/partials/taxe/create/create_taxe.html
- client/src/partials/taxe/create/create_taxe.js
- server/controllers/journal.js
- server/controllers/report.js
- server/controllers/uncategorised.js
- server/models/updates/imck/imck_synt.sql
Improve insertion in posting journal for the payroll,  Improve Payroll in OHADA reglement
> Payroll journal

- client/src/partials/reference/reference.js
- server/models/development/update/synt.sql
Update and improve unit reference
> Update and improve unit reference

- server/controllers/report.js
Fix error sql for incore report of primary cash
> Fix error sql for incore report of primary cash

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/cash/cashbox_account_currency/cashbox_account_currency.html
- client/src/partials/config_accounting/config_accounting.html
- client/src/partials/cotisation/config_cotisation/config_cotisation.html
- client/src/partials/cotisation/create/create_cotisation.html
- client/src/partials/donor_management/donor_management.html
- client/src/partials/fonction/fonction.html
- client/src/partials/grade_employers/grade_employers.html
- client/src/partials/hollydays/hollydays.html
- client/src/partials/offdays/offdays.html
- client/src/partials/payment_period/payment_period.html
- client/src/partials/price_list/pricelist.html
- client/src/partials/projects/projects.html
- client/src/partials/reference/reference.html
- client/src/partials/reference_group/reference_group.html
- client/src/partials/reference_group/reference_group.js
- client/src/partials/rubric/config_rubric/config_rubric.html
- client/src/partials/rubric/rubriques_payroll/rubriques_payroll.html
- client/src/partials/subsidy/subsidy.html
- client/src/partials/taxe/config_tax/config_tax.html
- client/src/partials/taxe/create/create_taxe.html
- client/src/partials/taxe/ipr/ipr.html
- client/src/partials/user_permission/permissions.html
Improve validation and invalidation of form and fix error
> Fix some form

- client/src/partials/reference/reference.html
- client/src/partials/reference/reference.js
- client/src/partials/reference_group/reference_group.html
- client/src/partials/reference_group/reference_group.js
Improve form and other condition of saving and updating forms
> Form improve

- client/src/partials/cash/cash.html
- client/src/partials/caution/caution.html
- client/src/partials/patient/debtor/swap.html
- client/src/partials/patient/edit/edit.html
- client/src/partials/patient/group/assignment.html
- client/src/partials/sales/sales.html
Addition a fonction in more modules for research a patient
> Addition a fonction in more modules for research a patient

- client/src/partials/reports/balance_mensuelle/balance_mensuelle.js
Improve code reduce six loop an a single loop, for the calculation of Sums
> Monthly balance

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/cash/extra_payment/extra_payment.html
- client/src/partials/cash/extra_payment/extra_payment.js
Improve module Extra paiement and rename this in Regularization paiement
> Improve extra paiement

- client/src/js/directives/findpatient.js
- server/controllers/patient.js
Adding element MiddleName during filtering patient for the research and improving sql request
> Research patient middle name

- plugins/mail/addresses/list.json
- plugins/mail/config.js
- plugins/mail/index.js
- plugins/mail/lib/mailer.js
- plugins/mail/reports/daily/lang/fr.json
- plugins/pluginManager.js
- server/config/environment/server.js
This PR moves the plugin configuration out of the server's general configuration and into each plugin's folder.  Additionally, the mail plugin's frequency has been updated to the correct (rather than testing) frequency.
> Move plugin configuration into plugins folder

- client/src/partials/patient/group/groups.html
Hiding the hypertext link to view the report for the groups of patients who do not have a price list
> Hiding the hypertext link to view the report for the groups of patients who do not have a price list

- client/src/i18n/en.json
- client/src/partials/journal_voucher/journal_voucher.html
- client/src/partials/journal_voucher/journal_voucher.js
This PR translates the Journal Voucher module, including server-sent errors into english.  French is still to be done by @DedrickEnc .
It also adds a feature that caches dirty voucher forms on submit, in case an error or other reason breaks the system.  This allows recovery at a later date identical to that in the sale module.
> Translate Journal Vouchers and auto-cache JV form

- client/src/partials/sales/sales.js
- plugins/pluginManager.js
- server/controllers/consumptionLoss.js
- server/controllers/createPurchase.js
- server/controllers/createSale.js
- server/controllers/finance.js
- server/controllers/journal.js
- server/controllers/patient.js
- server/controllers/serviceDist.js
- server/controllers/trialbalance.js
- server/controllers/uncategorised.js
- server/middleware/authentication.js
- server/middleware/projects.js
This PR prevents the bug introduced in the recent authentication PR #611 that blocks the user from posting.  Essentially, it changes all references on the server from `req.session.user_id` to the new model of `req.session.user.id`.
> Fix critical bug with session references on the server

- .gitignore
This PR fixes the broken .gitignore entries and removes outdated references.
> Clean up old .gitignore entries

- client/src/partials/user_permission/permissions.js
- server/config/routes.js
- server/controllers/users.js
This PR fixes a bug that inhibited a newly created user from logging in.  Specifically, we were not hashing (via MySQL's `PASSWORD()` function) the user password on creation.
> FIX: new users passwords are automatically hashed before inserted into database

- client/src/partials/cash/cashbox/cashbox.html
- client/src/partials/inventory/depot/depot.html
Little fix for checkboxe dysfunctional during Update
> Little fix for checkboxe dysfunctional during Update

- client/src/partials/user_permission/permissions.js
- server/config/routes.js
- server/controllers/users.js
- server/lib/db.js
This PR closes #639.  A fully functional user controller exists on the server side to handle create, update, and delete requests.
> Handle user creation, update, and deletion in a server-side user controller

- server/controllers/reports_proposed/reports.js
Very small error handling fixes. Closes #650
> Minor report fix

- client/src/i18n/en.json
- client/src/i18n/fr.json
fix and sanitaze translation file and complete translation file
> fix and sanitaze translation file and complete translation file

- client/src/index.html
- client/vendor/slickgrid.min.js
This PR fixes the broken slickgrid, a result of the new build system.  Apparently, we did not have slick.core.js, slick.grid.js, and several jquery ui modules.
> FIX: broken slickgrid dependencies

- client/src/js/services/ReportConfigService.js
- client/src/partials/reports_proposed/bilan/bilan.html
- client/src/partials/reports_proposed/bilan/bilan.js
- client/src/partials/reports_proposed/result_account/result_account.html
- client/src/partials/reports_proposed/result_account/result_account.js
- server/config/environment/server.js
- server/controllers/reports_proposed/data/account_result.js
- server/controllers/reports_proposed/data/bilan.js
- server/controllers/reports_proposed/lang/en.json
- server/controllers/reports_proposed/lang/fr.json
- server/controllers/reports_proposed/templates/account_result.dot
- server/controllers/reports_proposed/templates/bilan.dot
This PR contains :  
- correction of a balance formula to calculate balance by taking in account the account side (active or passive)
- creation of a report service to expose common data and function even if there is little data to expose for now
- internationalization of bilan pdf
- and many minors fixing
I preferred to keep both processAsset and processPassive function for clarity because each function has many lines, so using a conditional structure to join them will make one unclear big function.
> Amending bilan pdf report

- client/src/partials/rubric/rubriques_payroll/rubriques_payroll.html
- client/src/partials/taxe/create/create_taxe.html
- client/src/partials/taxe/create/create_taxe.js
Fixed malfunction of module taxes creation
> Fixed malfunction of module taxes creation

- client/src/partials/fiscal/fiscal.lock.js
Update select list for select only account ohada duiring lock fiscal year
> Update select list for select only account ohada duiring lock fiscal year

- client/src/partials/primary_cash/expense/multi_payroll.js
- client/src/partials/reports/payroll_report/payroll_report.html
- client/src/partials/reports/payroll_report/payroll_report.js
- client/src/partials/taxe/create/create_taxe.html
- Improved multi payroll module to prevent requettes the server for cofigurations that does not have data
- Fix form for create Taxe
> Improve payroll

- client/src/partials/reports/service_exploitation/service_exploitation.html
Fixed error in the formula of calculating Results
> Fixed error in the formula of calculating Results

- client/src/partials/reports/primary_cash/expense/expense_report.js
- client/src/partials/reports/primary_cash/income/income_report.js
- client/src/partials/reports/transactions/account.html
Removing appstate instead SessionService
> Removing appstate instead SessionService

- client/src/partials/journal/journal.grid.js
- client/src/partials/journal/journal.utilities.js
- server/controllers/finance.js
This PR fixes #713 .  It ensure that dates are properly interpreted on the client (slightly slower startup time), and introduces a new date formatter that is insensitive to time zones.  Finally, it also enables lower case filters for other values.
> Journal date filter behaves as expected

- client/src/partials/group_invoice/group_invoice.js
- client/src/partials/support/support.js
- server/controllers/journal/employee.js
- server/controllers/ledger.js
Fix Support of patient by employee and  by debitor
> Improve support patients

- client/src/partials/reports_proposed/employee_state/employee_state.html
- client/src/partials/reports_proposed/employee_state/employee_state.js
- server/controllers/reports_proposed/data/employee_state.js
- server/controllers/reports_proposed/lang/en.json
- server/controllers/reports_proposed/lang/fr.json
- server/controllers/reports_proposed/templates/employee_state.dot
The employee state is translated and used a service (reportConfigService) to share common data and behavior.
> Translating emplouyee state pdf report

- server/models/development/update/synt.sql
> Fixed duplicate key in synt.sql

- client/src/partials/creditor/creditor.html
- client/src/partials/creditor/creditor.js
- client/src/partials/purchase/create/purchase.js
- client/src/partials/receipts/receipts_unused.js
- server/models/development/update/synt.sql
- Remove column location_id from table supplier
- Update dependencies who use column location_id from supplier
> Update supplier management

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/cash/extra_payment/extra_payment.html
Fix Error of placeholder Text for regularizations of paiement
> Fix Error of placeholder Text for regularizations of paiement

- client/src/partials/reports/transactions/account.js
Fix transaction By acccount, error arround currency-id
> Fix transaction By acccount, error arround currency-id

- server/models/development/update/synt.sql
Removing of undeveloped reports
> Removing of undeveloped reports

- client/src/partials/price_list/pricelist.html
- server/models/development/update/synt.sql
- Fixed price list order element
- Fixed price list displaying is discount or apply label
- Village or quartier
- Enterprise name : Institut Medicale Chretien de Kananga
> Fixing Pricelist, village, enterprise

- server/controllers/journal/cash.js
- server/controllers/journal/finance.js
- server/models/development/update/synt.sql
In this PR : 
- We have fixed some erros which occur in sale discard or cash discard operations
> Fixing Sale and Cash discards

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/inventory/depot/depot.js
According to the meeting, depot suppression was his corrected and removing deprecated connect interface.
> Using session service, and Correction depot suppresing

- .gitignore
- client/src/partials/projects/project.js
- client/src/partials/projects/projects.html
This PR fixes the health zone select on the project management page to have expected behavior.  See commits for details.
> Fix: Project Health Zone <select> formatting and behavior

- server/controllers/finance.js
We have fixed the error with trans_id when we make transactions with journal voucher
> Fixing journal voucher trans_id

- server/controllers/journal/distribution.js
- server/controllers/serviceDist.js
In this PR, we have fixed an error which occur when we distribute medecine to service
> Fixing service distribution error

- client/src/partials/journal/journal.utilities.js
By caching the regular expression, and using re.test(), we gained some performance improvements as well.
> Fix(filter): Journal filter now case-insensative

- client/src/partials/purchase/authorization/authorization.html
- client/src/partials/purchase/validate/validate.html
- server/test/guid.spec.js
In this PR, we have fixed the text in button which exceed the allocated zone
> Fixing texts in purchase order validation and authorization

- server/controllers/consumptionLoss.js
- server/controllers/journal/distribution.js
In this PR we have fixed an error which was occurring when we make a stock loss operation
> Fixing stock loss error

- server/controllers/journal/fiscal.js
In this PR we have fixed : 
- An error which occur when we try to close a fiscal year
- Writing in the journal relative data of the fiscal year closed
> Fixing fiscal year closing

- server/controllers/reports_proposed/data/balance_sheet.js
- server/controllers/reports_proposed/templates/balance_sheet.dot
- server/controllers/reports_proposed/templates/style/reports.css
I've updated the balance sheet PDF report to filter for ohada
accounts.  The parent-child relationship has been made clearer, and
numeral formatting is applied to every line of the balance sheet.
> FIX(balance sheet): balance sheet rewrite

- server/controllers/trialbalance.js
This is a critical fix where the server would never report unbalanced
transactions resulting from a typo in the code.  This has been fixed.
Closes #785.
> FIX(trialbalance): prevent posting unbalanced transactions

- client/src/i18n/en.json
- client/src/i18n/fr.json
- server/models/development/update/synt.sql
In this PR, we have fixed the name of users and permissions module
> Fixing users and permissions name

- client/src/css/bhima.css
In this PR we have fixed the scrolling on side menu
> Fixing scroll overflow

- client/src/index.html
- client/src/partials/auth/login.js
- client/src/partials/bhima/application.js
- client/src/partials/home/home.js
This commit ensures that the application has an exchange rate on
startup.  It also makes some minor controller as syntax changes to
affected modules.
Fixes #682.
> FIX(exchange rate): ensure exchange rate loading

- client/src/partials/journal_voucher/journal_voucher.html
- client/src/partials/journal_voucher/journal_voucher.js
- server/controllers/finance.js
This commit adds the ability to retotal a journal voucher when the
voucher loaded from stored data.
I've also updated the controller to use $inject syntax while I was
there.  Notably, `self` --> `vm`, to standardize our controllers.
Fixes #816.
> FIX(voucher totals): Retotal voucher on recovery

- README.md
This commit adds badges for dependency management to the README.
> FEAT(david-dm): dependency management

- client/src/js/app.js
- client/src/partials/caution/caution.html
- client/src/partials/caution/caution.js
- client/src/partials/journal_voucher/journal_voucher.css
This commit contains significant enhancements to the caution controller
and UI.
1. Cautions use controller as syntax
2. AngularJS for form validation.
3. Validation happens both in real time and at submit.  If an invalid
form is submitted, an error message is shown.
4. The find-patient can be refreshed.
5. `<address>` for semantic HTML.
6. Patient information form fields line up.
7. Improvements to cashbox + currency lookups
8. `.help-block` reverted to regular bootstrap behavior
> UI(caution): improvements to caution UI

- client/src/js/app.js
- client/src/partials/exchange_rate/exchange_rate.html
- client/src/partials/exchange_rate/exchange_rate.js
This commit rewrites the exchange controller.  The following changes
have been introduced:
1. Simpler date changes and validation in the controller code
2. Use AngularJS form validation
3. Dates render properly in the client (fixes #588)
4. Fixes #673.
> FIX(exchange rate): rewrite exchange controller

- utilities/account/fixing_parent/fixingAccountParent.js
This PR fix account parent according their group, either is_ohada accounts or other accounts
> Fixing unit parent according is_ohada property

- client/src/partials/depots/distributions/patients/patient.js
- client/src/partials/depots/distributions/patients/patients.html
- client/src/partials/fiscal/fiscal.create.js
- client/src/partials/fiscal/fiscal.js
- client/src/partials/fiscal/fiscal.lock.html
- client/src/partials/fiscal/fiscal.lock.js
- server/controllers/fiscal.js
- server/controllers/ledger.js
In this PR the patient distribution is fixed, there was an error introduced naively and that is bad.
I also noticed that the fiscal year code was changed to use aliasing but even there the change was not right.
I forced user to post all fiscal year data to the general ledger before closing the fiscal year, I also removed the period zero
> Fixing patient distribution and fiscal year process

- client/src/partials/journal/journal.controls.js
- client/src/partials/journal/journal.grid.js
- client/src/partials/journal/journal.utilities.js
- server/controllers/uncategorised.js
This PR gives the possibility to user to repost a transaction.
> Reposting a transaction

- client/src/i18n/fr.json
- client/src/index.html
- client/src/partials/purchase/authorization/authorization.js
- client/src/partials/purchase/confirm/confirm.js
- client/src/partials/purchase/create/purchase.html
- client/src/partials/purchase/validate/validate.js
- client/src/partials/receipts/receipt.purchase.js
- server/controllers/journal/core.js
In this PR, I removed the ng-strict-di directive temporarily and fix some issue about date and so one ...
> Minors fixes in purchase order modules

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/stock/dashboard/dashboard.html
- client/src/partials/stock/dashboard/dashboard.js
- server/models/development/update/synt.sql
This commit adds proper behavior to loading indicators on the stock
dashboard page, causing them to disappear if there is no data loaded.
We also add a message to the user, indicating that no data was found.
Finally, we've updated the SQL link to the stock management page, which
was recently broken.
> FIX(stock dashboard): proper loading indicators

- server/controllers/journal/primarycash.js
Fixes #850.
This commit fixes critical SQL errors prevent both the payment and
partial payment of salaries.
> FIX(salary payment): Fix bugs in salary payment

- client/src/js/app.js
- client/src/partials/primary_cash/expense/payday_advance.html
- server/controllers/journal/primarycash.js
Fixes #851.
This commit patches two bugs, the first reported in #851 and a second
validation bug that was discovered during testing.  The former bug was
due to ill-formed SQL and poor parameter passing to db.exec().  The
second bug allowed the user to insert a string into a number field.
> FIX(salary advance): Fix bugs in advance

- client/src/partials/journal_voucher/journal_voucher.html
This commit adds success and warning colors to the validation messages
that are presented to the user while editing and submitting the journal
voucher form.
> FIX(voucher ui): pretty colors for validation msgs

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/accounts/create_account/create.html
- client/src/partials/accounts/create_account/create.js
- client/src/partials/journal_voucher/journal_voucher.html
In this PR, I restricted the user to don't use the future date to pass a transaction and remove the dependence to account_number in account
> Amending account and journal voucher functionnality

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/reports/global_transaction/global_transaction.html
- client/src/partials/reports/global_transaction/global_transaction.js
In this PR, we have made : 
- Aliasing module `Global Transaction`
- Cleaning of code
- Currency option
- Account order in select box
> Fixing Global Transactions Module

- client/src/js/app.js
- client/src/partials/employee/employee.html
- client/src/partials/employee/employee.js
This commit fixes the following issues in the employee controller:
1. Use loading indicators (#726)
2. Use newer connect API (#836)
3. Cleaner HTML.
> CHORE(employee): miscellaneous fixes

- client/src/index.html
- client/src/partials/dashboard/finance.js
- server/controllers/analytics/cashflow.js
This commit fixes the finance dashboard's SQL to calculate debtor group totals.  There might possibly be a performance improvement here as well.
> FIX(finance dashboard): wrong debtor group totals

- client/src/js/app.js
- client/src/partials/user_permission/permissions.css
- client/src/partials/user_permission/permissions.html
- client/src/partials/user_permission/permissions.js
Fixes #882.  Fixes #880.
This commit fixes various permissions bugs and ui quirks.
1. Use loading indicators for users list
2. Limit height of users & permissions lists
3. Do not send passwords to client (#882)
4. Convert username to lower case (#880)
> FIX(permission): miscellaneous permission fixes

- client/src/partials/caution/caution.html
- client/src/partials/caution/caution.js
- server/controllers/report.js
This commit fixes several mistakes in the caution controller:
1. Currencies/Cashboxes now properly load for the first time and on
refresh.
2. If a debtor's account has a positive balance, a warning message is
displayed.
3. The submit button is disabled until a currency is chosen.
> FIX(caution): misc fixes

- client/src/partials/patient/search/search.html
- client/src/partials/patient/search/search.js
This commit improves the UI/UX of the patient search by:
1. removing most listeners on the results table (speed improvements)
2. ensure that icons are rendered on correct fields
3. loading icon spins!
**NOTE** This commit applies to the patient search module (`/patient/search/`) not the `<find-patient>` directive.
> CHORE(patient search): ui/ux improvements

- client/src/partials/patient/debtor/swap.html
- client/src/partials/patient/debtor/swap.js
This commit fixes misc bugs in the debtor group reassignment module (`/patient/debtor/`)
1. The patient's address/location is properly displayed
2. $scope watchers removed (duplication)
3. Cleaner HTML
> CHORE(reassign debtor): misc fixes in debtor group

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/auth/login.html
- client/src/partials/auth/login.js
- server/controllers/auth.js
Fixes #681.
This commit adds a check to ensure the user has permissions before login
into bhima. If the user does not have any permissions, we display an error
telling them to contact the system administrator.
**Screenshot** (FR)
> FIX(login): prevent permissionless login

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/reports/account_statement/account_statement.html
- client/src/partials/reports/account_statement/account_statement.js
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.css
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.html
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.js
- client/src/partials/reports/chart_of_accounts/chart.html
- client/src/partials/reports/chart_of_accounts/chart.js
- client/src/partials/reports/global_transaction/global_transaction.js
- client/src/partials/reports_proposed/grand_livre/grand_livre.html
- client/src/partials/reports_proposed/grand_livre/grand_livre.js
- server/controllers/report.js
This PR fixes the following reports:
1. Account Statement
2. Chart of Accounts
3. General Ledger
4. Monthly Balance
For all these reports, I've cleaned up the HTML, removing invalid CSS rules, deleting extra elements, ensuring elements line up, and adding loading indicators. 
In Account Statement, I've also replace UUIDs with Trans IDs.
> Miscellaneous Accounting Report Fixes

- client/src/js/app.js
- client/src/partials/cash/cash.html
- client/src/partials/cash/cash.js
This commit fixes a regression caused by improper use of
$watchCollection.  It also introduces some HTML fixes to the cash
payments module.
> FIX(cash): correct currency exchange

- client/src/js/app.js
- client/src/partials/debtor/debtor_group.html
- client/src/partials/debtor/debtor_group.js
This commit adds slight performance improvements to the debtor group
module by replacing ng-repeat options with ng-options.  It also cleans
up the HTML and styling slightly for a better UX.
> CHORE(debtor group): performance improvements

- client/src/partials/reports_proposed/debitor_group_report/debitor_group_report.html
- server/controllers/reports_proposed/data/debitor_group_report.js
- server/controllers/reports_proposed/templates/debitor_group_report.dot
In this PR, I fix the pdf report of debitor group state to print the header.
> Fixing the debitor group state

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.html
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.js
- client/src/partials/reports/operating_account/operating_account.html
- client/src/partials/reports/operating_account/operating_account.js
- package.json
- server/controllers/report.js
This commit restructures the balance_mensuelle report to pull data from
only the period totals table, rather than the combined posting_journal
and general_ledger.  This change ensures that we are dealing with only
general_ledger data.
> FIX(balance mensuelle): Fixes report summation bug

- .jshintrc
- .travis.yml
- package.json
- sh/travis.sh
This commit adds linting of the client and server to the Travis CI
tests for an acceptable PR.  The server currently does not pass lint
checks and these will be addressed in coming pull requests.
> CHORE(travis): lint repository during build

- client/src/partials/primary_cash/primary.html
- client/src/partials/primary_cash/primary.js
This PR fixes message of required exchange rate in Primary Cash Module
> Fixing primary cash daily rate message

- client/src/js/app.js
- client/src/partials/primary_cash/income/support/support.html
- client/src/partials/primary_cash/income/support/support.js
- server/controllers/journal/primarycash.js
This commit fixes some critical bugs in the employee payment page that
prevents employees from paying debtor's bills.  These bugs are:
1. Typos in the $inject that prevent SessionService from being injected
2. Typos in journal.js that prevent the proper currency ID from being
inserted.
> FIX(primary cash): employee support payments

- client/src/partials/accounts/create_account/create.html
In this PR, I fixed the account page to deal with the reference for generating bilan and compte resultat
> Fixing account page to deal with reference.

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/config_accounting/config_accounting.html
- client/src/partials/config_accounting/config_accounting.js
- client/src/partials/employee/employee.html
- client/src/partials/employee/employee.js
- client/src/partials/hollydays/hollydays.html
- client/src/partials/hollydays/hollydays.js
- client/src/partials/offdays/offdays.html
- client/src/partials/offdays/offdays.js
- client/src/partials/rubric/rubriques_payroll/rubriques_payroll.html
- client/src/partials/rubric/rubriques_payroll/rubriques_payroll.js
- server/controllers/journal/employee.js
This PR fix : 
- Payroll/Configuration : Erreur de reference ER_NO_REFERENCE_ROW_2 
- Payroll/Employee : Erreur avec les dates
- Payroll/Hollyday : Erreur de reference ER_NO_REFERENCE_ROW_2 
- Payroll/Offday : Erreur avec les dates
- Payroll/Rubriques
- Payroll/Multipayroll : Ecriture dans le journal lors d'un engagement de paiement de taxe entreprise
> Fixing bugs in Payroll module

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports_proposed/result_account/result_account.html
- client/src/partials/reports_proposed/result_account/result_account.js
- server/controllers/reports_proposed/data/account_result.js
- server/controllers/reports_proposed/lang/fr.json
- server/controllers/reports_proposed/templates/account_result.dot
- server/controllers/reports_proposed/templates/bilan.dot
Amending result account pdf report
> Fixing result account pdf report

- server/controllers/trialbalance.js
This is a critical fix to the trial balance, ensuring that period totals
are correctly calculated and stored in the appropriate periods.
> FIX(trial balance): group by respects period ids

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/primary_cash/primary.html
- client/src/partials/primary_cash/primary.js
- client/src/partials/reference/reference.html
This PR fix : 
- translations
- daily rate message in primary cash
> Daily rate message

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/services/exportFile.js
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.html
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.js
- server/controllers/report.js
This Pr fixes the balance mensuelle report.
> Fixing balance mensuelle

- server/models/development/bhima_structure.sql
new bhima_structure and bhima_data
> New data for development

- client/src/partials/reports/balance_mensuelle/balance_mensuelle.js
- utilities/unpost/unpost.sql
> fixing report

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/depots/distributions/patients/patient.js
- client/src/partials/depots/distributions/patients/patients.html
- client/src/partials/sales/sales.html
- client/src/partials/sales/sales.js
- server/controllers/depot.js
- server/controllers/ledger.js
- server/models/development/update/synt.sql
In this Pr I fixed the stock distribution to patient, I changed a request which was not so clear, I fixed some translation issue, correct some database issue
> fixing patient distribution

- client/src/partials/receipts/receipt.sale.js
- client/src/partials/receipts/templates/receipt_sale.html
- client/src/partials/records/sales_records/sales_records.html
- client/src/partials/records/sales_records/sales_records.js
- server/config/routes.js
- server/controllers/ledger.js
- server/controllers/report.js
This PR fix : 
- The project abbreviation in sale receipt
- The patient project abbreviation in sale record
- The sale balance in sale receipt
> Fixing receipt project

- client/src/partials/depots/distributions/patients/patient.js
- server/controllers/journal/cash.js
URGENT: This commit ensures that the proper IDs are set in the cash journal
route. Previously, no gain/loss on exchange or rounding was being
calculated do to an undefined cash id.  This commit fixes this critical
bug.
> FIX(cash): broken ID in cash journal route

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/reports/patient_visit_status/patient_visit_status.css
- client/src/partials/reports/patient_visit_status/patient_visit_status.html
- client/src/partials/reports/patient_visit_status/patient_visit_status.js
- server/controllers/report.js
- server/models/update/synt.sql
This PR add a report of patients visitations, it's include a generation of chart with Chart.js;
> Patient Visit Status

- client/src/partials/stock/integration/confirm_integration/confirm_integration.html
- server/controllers/cashflow.js
This PR fix the link to the receipt of an integration
> Fixing receipt link in confirm integration report

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/patient/registration/registration.html
- client/src/partials/patient/registration/registration.js
- client/src/partials/reports/patient_visit_status/patient_visit_status.html
This PR fix : 
- Patients visitation registrations
- Totals in Patents Visitations Report
> Fixing Patient registration visit and visit status

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/js/services/transactionSource.js
- client/src/partials/primary_cash/expense/generic.js
- client/src/partials/reports/cash_flow/cash_flow.css
- client/src/partials/reports/cash_flow/cash_flow.html
- client/src/partials/reports/cash_flow/cash_flow.js
- server/config/routes.js
- server/controllers/cashflow.js
- server/controllers/report.js
- server/models/development/update/synt.sql
This PR add a cash flow report in Fianace module
> Cash Flow Report 

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/depots/depots.js
- client/src/partials/patient/registration/registration.js
- client/src/partials/stock/integration/integration.js
- client/src/partials/stock/service_return_stock/service_return_stock.html
- client/src/partials/stock/service_return_stock/service_return_stock.js
- server/controllers/depot.js
- server/controllers/journal.js
- server/controllers/journal/inventory.js
- server/models/update/synt.sql
This PR add an new module for returning medecines from service to a depot
> Service return medicines

- client/src/js/app.js
- client/src/partials/reports/donation/donation.html
- client/src/partials/reports/donation/donation.js
- client/src/partials/stock/dashboard/dashboard.html
- client/src/partials/stock/donation_management/donation_management.html
- client/src/partials/stock/donation_management/donation_management.js
- server/controllers/inventory/donations.js
This PR fix donations modules and reports
> fixing donations modules

- client/src/js/app.js
- client/src/partials/grade_employers/grade_employers.js
- client/src/partials/primary_cash/expense/multi_payroll.js
- client/src/partials/reports/stock_integration/stock_integration.html
- client/src/partials/reports/stock_integration/stock_integration.js
- client/src/partials/stock/service_return_stock/service_return_stock.html
- client/src/partials/stock/service_return_stock/service_return_stock.js
This PR, fix : 
- Service return : remove details of the movement in the view
- Report confirm integration 
- Payroll : pretty comment in the IPR section when submit
> Fix: service return, report integration, payroll

- client/src/partials/stock/service_return_stock/service_return_stock.js
- server/controllers/purchase.js
- server/controllers/report.js
- server/controllers/uncategorised.js
- server/models/update/synt.sql
Thir PR add the is_return column in purchase table
> Fix(service_return_stock): Using is_return in purchase

- client/src/partials/patient/registration/registration.js
> Fixing patient visit button

- client/src/partials/primary_cash/expense/cotisation_payment.js
- client/src/partials/reports/employee_standing/employee_standing.html
- client/src/partials/reports/employee_standing/employee_standing.js
- server/controllers/report.js
This PR fix the employee standing report
> Fixing employee standing report

- client/src/partials/reports/patient_visit_status/patient_visit_status.js
- client/src/partials/stock/donation_management/donation_management.js
This PR fix patient visit report and donation management linting errors
> Fix(lint) : Chart and donation linting errors

- client/src/i18n/fr.json
- client/src/partials/reports/operating_account/operating_account.js
- server/controllers/reports/report_legacy.js
- Changing the Display of the operating account report,displaying the result on the load column or profit and hiding the account for which the charge is equal to the benefit
- Imporve translate file
> Improve report operating account

- client/src/js/app.js
- client/src/partials/reports/donation/donation.js
- server/models/update/synt.sql
- Fix and Improve unit Report of Donation
- Add reference of unit Patient Visit Status 
- Deleting report stock_store in main tree
> Fix and Improve unit Report of Donation, Add reference of unit Patient Visit Status , Deleting report stock_store in main tree

- .travis.yml
- README.md
- package.json
- server/controllers/categorised/inventory_depreciate.js
- server/controllers/categorised/payroll.js
- server/controllers/categorised/reports_depreciate.js
- server/controllers/categorised/subsidies.js
- server/controllers/finance/cotisationPayment.js
- server/controllers/finance/donations.js
- server/controllers/finance/extraPayment.js
- server/controllers/finance/journal.js
- server/controllers/finance/postingDonation.js
- server/controllers/finance/synthetic.js
- server/controllers/finance/taxPayment.js
- server/controllers/medical/patient.js
- server/controllers/medical/snis.js
- server/controllers/reports/report_legacy.js
- server/controllers/stock/depot.js
- server/lib/db.js
- server/lib/pluginManager.js
- sh/travis.sh
This commit makes Travis lint PRs.  Once the initial round of lint fixes lands, we should only accept PRs that pass lint requirements.
**TODOs**
> BUILD(travis): make travis lint the repo

- README.md
- package.json
This commit bumps the version and changes the badge links to reflect the 1.X/2.X split.
> CHORE(version): version bump and badge update

- client/src/partials/reports/patient_visit_status/patient_visit_status.css
- client/src/partials/reports/patient_visit_status/patient_visit_status.html
- client/src/partials/reports/patient_visit_status/patient_visit_status.js
This PR fixes chart colors for printing
> Color fixation for print

- client/src/partials/reports/primary_cash/expense/expense_report.html
- server/controllers/report.js
This PR enhance the sql query for the expense report in primary cash
> Enhancing expense and income report

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/snis/reports/step1.html
- client/src/partials/snis/reports/step2.html
- client/src/partials/snis/reports/step3.html
- client/src/partials/snis/reports/step4.html
- client/src/partials/snis/reports/step5.html
- client/src/partials/snis/reports/step6.html
- client/src/partials/snis/reports/step7.html
- client/src/partials/snis/reports/step8.html
- client/src/partials/snis/reports/step9.html
- client/src/partials/snis/snis.html
- client/src/partials/snis/snis.js
- client/src/partials/snis/snis_new_report.css
- client/src/partials/snis/snis_print_report.html
- client/src/partials/snis/snis_print_report.js
- debtor_transactions.txt
This PR enhance the electronic snis form and report for to be used quickly
> Snis electronic form and reports

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.html
- client/src/partials/reports/balance_mensuelle/balance_mensuelle.js
- server/controllers/report.js
This PR add a mean for selecting balance by period plage
> Monthly Balance by period plage

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/primary_cash/income/income_report.html
- client/src/partials/reports/primary_cash/income/income_report.js
- client/src/partials/reports/primary_cash/templates/income_expense.modal.html
- client/src/partials/reports/primary_cash/templates/income_expense.modal.js
- server/controllers/report.js
This PR fix the income and expense report modules with a modal box for finding receipts
> Report for income and expenses

- client/src/partials/journal/journal.controls.js
This PR update the journal.control.js for that it's doesn't update the origin of transactions
> Dont update the origin of transactions

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/services/transactionSource.js
> Cashflow : Update mapping names

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/customer_debt/customer_debt.css
- client/src/partials/reports/customer_debt/customer_debt.html
- client/src/partials/reports/customer_debt/customer_debt.js
- server/controllers/customer_debt.js
Harmonizing values with correct balance
> Customers Debts : Harmonizing values with correct balance

- client/src/partials/reports/cash_flow/cash_flow.js
- server/controllers/cashflow.js
Enhancing to exact balance with reports considerations
> Cashflow: Enhancing to exact balance with reports considerations

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/js/app.js
- client/src/partials/reports/service_status/service_status.css
- client/src/partials/reports/service_status/service_status.html
- client/src/partials/reports/service_status/service_status.js
- client/src/partials/reports/service_status/templates/service_billing.modal.html
- client/src/partials/reports/service_status/templates/service_billing.modal.js
- server/config/routes.js
- server/controllers/serviceStatus.js
- server/models/update/synt-tshikaji.sql
- server/models/update/synt.sql
This PR add a report for billing by service
> Service billing status

- client/src/partials/reports/service_status/service_status.html
- client/src/partials/reports/service_status/service_status.js
> Service Status: Removing cost values

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/cash_flow/cash_flow.html
- client/src/partials/reports/service_status/service_status.html
- client/src/partials/reports/service_status/service_status.js
- server/controllers/serviceStatus.js
This PR add a report for billing by service
> Billing status : Service billing in general ledger

- client/src/partials/reports/service_status/service_status.html
- server/controllers/serviceStatus.js
> Service billing status : Removing commented queries

- client/src/partials/primary_cash/expense/multi_payroll.js
Changing the formula to calculate the IPR by calculating the basis of IPR by net pre-tax amount of the INSS coast employee share
@DedrickEnc
> Fix and Update IPR calculation

- server/controllers/depot.js
Fix sql query for getting available stock level by lot and by Store
@DedrickEnc
> Fix sql query for getting available stock level by lot and by Store

- client/src/partials/primary_cash/expense/multi_payroll.js
- client/src/partials/primary_cash/expense/purchase.js
- client/src/partials/primary_cash/income/support/support.js
- client/src/partials/purchase/authorization/authorization.html
- client/src/partials/purchase/confirm/confirm.html
- client/src/partials/purchase/create/purchase.html
- client/src/partials/purchase/create/purchase.js
- client/src/partials/purchase/validate/validate.html
- client/src/partials/reports/employee_standing/employee_standing.html
- client/src/partials/reports/patient_standing/patient_standing.html
- client/src/partials/reports/payroll_report/payroll_report.html
- server/controllers/journal/convention.js
- server/controllers/journal/employee.js
- server/controllers/journal/purchase.js
- server/controllers/ledger.js
Improve some modules, and showing data, reports 
@DedrickEnc
> Fix improve module

- client/src/i18n/fr.json
- client/src/partials/depots/distributions/cancel/cancel.js
- client/src/partials/depots/reports/distributions/templates/losses.html
- client/src/partials/depots/reports/distributions/templates/patients.html
- client/src/partials/depots/reports/distributions/templates/services.html
- client/src/partials/reports/stock_status/stock_status.js
- server/config/routes.js
- server/controllers/depot.js
- server/controllers/inventory/consumption.js
- server/controllers/inventory/core.js
- server/controllers/inventory/stock.js
- server/controllers/report.js
Fix the cancel distribution
Fix the cancelling of stock losse
Fix the cancelling Patient Distribution
Fix the cancelling Service Distribution
Fix and Improve the stock report in Stock Status
Improve SQL request the getting many kind of data around Stock
@DedrickEnc
> Fixing arround stock management

- client/src/partials/hollydays/hollydays.js
- client/src/partials/reports/employee_standing/employee_standing.html
- client/src/partials/reports/patient_standing/patient_standing.html
- employee_standing/employee_standing.js
- server/controllers/journal/employee.js
Adding transtationID in report for Employee and Patient Standing, Improve the hollyday for the Locked Employee
@DedrickEnc
> Adding transtationID in report for Employee and Patient Standing, Improve the hollyday for the Locked Employee

- client/src/i18n/en.json
- client/src/i18n/fr.json
- client/src/partials/reports/cash_flow/cash_flow.html
- client/src/partials/reports/cash_flow/cash_flow.js
- server/controllers/cashflow.js
This PR add an option for cashflow report to produce cashes (CDF and USD) report
> Cashflow synthetic report

- client/src/js/services/ReportConfigService.js
- client/src/partials/reports/transactions/account.html
- client/src/partials/reports_proposed/debitor_group_report/debitor_group_report.html
- client/src/partials/reports_proposed/debitor_group_report/debitor_group_report.js
- package.json
- server/config/environment/server.js
- server/controllers/reports_proposed/data/debitor_group_report.js
- server/controllers/reports_proposed/templates/debitor_group_report.dot
This commit improves the "debitor groups report" by allowing printing in FCs, as well as orders the values correctly.
NOTE - you will need to run npm install to upgrade numeraljs.
> Refactor: debtor groups report
